FROM node:20-alpine as build

WORKDIR /app

COPY backend/package*.json ./

RUN npm ci

COPY backend/src ./src
COPY backend/tsconfig.json .

RUN npm run build

FROM node:20-alpine

WORKDIR /app

COPY backend/package*.json ./

RUN npm ci --only=production

COPY --from=build /app/dist ./dist

EXPOSE 3000

CMD ["npm", "start"]
